{
 "title": "testsrc",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ydiff",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ydif", "legendFormat": "{{job}}" },
    {}
   ]
  },
  {
   "title": "y average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "yavg", "legendFormat": "{{job}}" },
    {}
   ]
  },
  {
   "title": "saturation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "satavg", "legendFormat": "{{job}}" },
    {}
   ]
  },
  {
   "title": "noise",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bitplanenoise01", "legendFormat": "{{job}}" },
    {}
   ]
  }
 ]
}